INSERT INTO grant_sources (name, description, url) VALUES
('Zephyr Angels LinkedIn', 'Можности за финансирање и објави од Zephyr Angels на LinkedIn', 'https://www.linkedin.com/company/zephyr-angels/posts/?feedView=all'),
('Impact Ventures', 'Венчур капитал и инвестициски можности во Северна Македонија', 'https://impactventures.mk/'),
('Бизнис Ангели Македонија', 'Мрежа на бизнис ангели за стартапи во Македонија', 'http://biznisangeli.mk/?fbclid=IwY2xjawI33XtleHRuA2FlbQIxMAABHbB84BnkAsfx36CGju3t6axzFl_l_MI2qF_CNZc-iU4z1e1-g8iMQci-ng_aem_4AlEGWIxP50iDcsWu4b8vg'),
('Министерство за економија', 'Владини грантови и програми за економски развој', 'https://www.economy.gov.mk'),
('SeeLegal', 'Правна поддршка и финансирање за стартапи', 'seelegal.org'),
('Министерство за животна средина и просторно планирање', 'Еколошки грантови и можности за финансирање', 'https://www.mep.gov.mk/category/?id=1123'),
('Министерство за образование и наука', 'Образовни грантови и финансирање за истражување', 'https://mon.gov.mk'),
('Seavus Accelerator', 'Програма за акцелерација на стартапи', 'https://seavusaccelerator.com'),
('Младински економски самит', 'Младинско претприемништво и иницијативи за финансирање', 'http://www.yes.org.mk/Default.aspx?r=6&l=54&c=22'),
('CEED Hub', 'Центар за претприемништво и извршен развој', 'https://ceedhub.mk'),
('Привредна банка', 'Банкарски и финансиски услуги за бизниси', 'https://www.pcb.mk/private-clients.nspx'),
('Crimson Capital', 'Инвестиции и финансирање за бизниси', 'https://www.crimsoncapital.org/home.asp'),
('EU Startups', 'Европска платформа за финансирање и инвестиции во стартапи', 'https://eu-startups.com'),
('Европска инвестициска банка', 'Европски програми за финансирање и кредити', 'https://www.eib.org/en/products/loans/index.htm'),
('ЕБРД - Фонд за зелена економија', 'Зелено финансирање и одржлив развој', 'ebrdgeff.com'),
('Хоризонт Европа - Северна Македонија', 'ЕУ финансирање за истражување и иновации во Северна Македонија', 'https://research-and-innovation.ec.europa.eu/strategy/strategy-research-and-innovation/europe-world/international-cooperation/association-horizon-europe/north-macedonia_en'),
('Инвестициски рамковен договор за Западен Балкан', 'Инвестициски рамковен договор за проекти во Западен Балкан', 'https://wbif.eu/project/PRJ-MULTI-PRI-001'),
('Грантови од Европската служба за надворешни работи', 'ЕУ грантови за Северна Македонија', 'https://www.eeas.europa.eu/eeas/grants_en?f%5B0%5D=grant_site%3ANorth%20Macedonia&s=229'),
('SC Ventures', 'Венчур капитал и инвестиции во стартапи', 'https://sc-ventures.com'),
('11.VC', 'Фирма за венчур капитал', 'https://www.11.vc'),
('OpenVC', 'Отворена платформа за венчур капитал', 'openvc.app'),
('Централен електронски регистар на јавни набавки', 'Јавни набавки и тендерски можности', 'https://e-nabavki.gov.mk/PublicAccess/home.aspx#/notices'),
('Tender Impulse Македонија', 'Тендери и набавки за Македонија', 'https://tenderimpulse.com/all-tender-list-from-country/get-macedonia-tenders/2025-07-28/1'),
('REDI NGO Тендери', 'Тендерски можности за НВО', 'https://redi-ngo.eu/tenders/'),
('Tenders on Time Македонија', 'Навремени информации за тендери во Македонија', 'https://www.tendersontime.com/macedonia-tenders/'),
('Bid Detail Македонија', 'Детални информации за понуди во Македонија', 'https://www.biddetail.com/macedonia-tenders'),
('Development Aid Тендери', 'Развојна помош и тендерски можности', 'https://www.developmentaid.org/tenders/search?locations=272'),
('Tenderi.mk', 'Македонски портал за тендери', 'https://tenderi.mk/'),
('Централен завод за финансирање и договарање', 'Владини можности за финансирање и договарање', 'https://cfcd.finance.gov.mk/?page_id=4750&lang=en'),
('ЕУ портал за финансирање и тендери', 'Финансирање и тендери од Европската комисија', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home'),
('Слвесник Тендери', 'Службен весник - тендерски објави', 'https://www.slvesnik.com.mk/tenderi.nspx#'),
('Euro-Access', 'Европски онлајн портал кој собира можности за финансирање од ЕУ програми', 'https://euro-access.eu/en'),
('WeBalkans Можности', 'ЕУ-базиранa платформа која листа финансирање, стипендии и можности за организации и поединци од Западен Балкан', 'https://webalkans.eu/en/opportunities/'),
('Western Balkans Investment Framework (WBIF)', 'Заедничка финансиска иницијатива на ЕУ, меѓународни финансиски институции и влади на Западен Балкан за поддршка на социо-економскиот развој', 'https://wbif.eu'),
('ЕУ Повици за Предлози', 'Официјален портал за финансирање и тендери на Европската комисија со отворени повици за предлози', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals?isExactMatch=true&status=31094501,31094502,31094503&frameworkProgramme=43252405&order=DESC&pageNumber=1&pageSize=50&sortBy=startDate'),
('EBRD Green Economy Financing Facility (GEFF)', 'Иницијатива на ЕБРД за зелено финансирање и техничка поддршка во Северна Македонија', 'https://ebrdgeff.com/?country%5B%5D=36'),
('ProCredit Bank - StartAPI', 'Банкарски пакет за поддршка на стартапи и претприемачи', 'https://www.pcb.mk/startapi.nspx'),
('ProCredit Bank - Пакет за Млади Претприемачи', 'Специјален финансиски програм на ProCredit Bank за млади претприемачи', 'https://www.pcb.mk/paket-mladi-pretpriemaci.nspx'),
('ProCredit Bank - Пакет за Жени Претприемачи', 'Банкарски пакет за финансиска поддршка на жени претприемачи', 'https://www.pcb.mk/paket-za-zeni-pretpriemaci.nspx'),
('GIZ Nabavki', 'Платформа за набавки на Германската агенција за развој (GIZ)', 'https://ausschreibungen.giz.de/Satellite/company/welcome.do'),
('UNDP Nabavki', 'Портал за набавки на Програмата за развој на ОН', 'https://procurement-notices.undp.org/'),
('IPARD - Платежна Агенција', 'Инструмент за претпристапна помош за рурален развој во Северна Македонија', 'https://ipard.gov.mk/mk/pocetna/'),
('Министерство за Труд и Социјална Политика - IPA Програми', 'Портал со ЕУ-финансирани IPA програми во Северна Македонија', 'https://mtsp.gov.mk/ipa.nspx'),
('LaunchHub', 'Стартап акцелератор и инвестициски програми', 'https://launchub.com'),
('ProCredit Bank', 'Банкарски услуги и кредити за МСП', 'https://procredit.com.mk'),
('CFCD Финансирање и договарање - IPA II', 'ЕУ програми за претпристапна помош - компонента II', 'https://cfcd.finance.gov.mk/tenders/publicTender/home'),
('CFCD Финансирање и договарање - IPA III', 'ЕУ програми за претпристапна помош - компонента III', 'https://cfcd.trinitymedia.mk/client/public/dashboard'),
('DNB Македонија - SeeLegal', 'Правни услуги и консалтинг за бизниси', 'https://dbnm.seelegal.org'),
('EIT Food Иновации', 'Европски институт за иновации и технологија - храна', 'https://www.eitfood.eu/blog'),
('Erasmus+ Национална Агенција', 'Официјална агенција за Erasmus+ програми во Северна Македонија', 'https://na.org.mk'),
('Хоризонт Европа - Македонија', 'Рамковна програма на ЕУ за истражување и иновации', 'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en'),
('ЕУ Делегација - Грантови', 'Грантови и програми на ЕУ делегацијата во Северна Македонија', 'https://www.eeas.europa.eu/north-macedonia/eu-delegation-grants_en'),
('ЕУ Портал за Финансирање и Тендери', 'Централен портал за сите ЕУ можности за финансирање', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals'),
('Слвесник - Тендерски Објави', 'Службен весник на Република Северна Македонија - тендери', 'https://www.slvesnik.com.mk/tenderi.nspx'),
('E-Набавки Портал', 'Централен електронски систем за јавни набавки', 'https://e-nabavki.gov.mk/PublicAccess/home.aspx'),
-- Missing sources from html_dumps
('Launchub Bulgaria', 'Регионален стартап акцелератор и инвестициски фонд', 'https://launchub.bg'),
('Zefyr Angels', 'Мрежа на бизнис ангели во регионот', 'https://zefyr.eu'),
-- Missing sources that match our aggregate.js parsers
('CFCD Тендери - IPA II', 'Централен завод за финансирање - јавни тендери IPA II', 'https://cfcd.finance.gov.mk/tenders/publicTender/home'),
('CFCD Контрол панел - IPA III', 'Централен завод за финансирање - контрол панел IPA III', 'https://cfcd.trinitymedia.mk/client/public/dashboard'),
-- Additional EU sources
('ЕУ Делегација Грантови', 'Грантови од ЕУ делегацијата во Северна Македонија', 'https://eeas.europa.eu/delegations/north-macedonia/grants_en'),
('ЕУ Фондови и Тендери - Почетна', 'Главен портал за ЕУ финансирање', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home'),
('Хоризонт Европа - Основна страница', 'Рамковна програма за истражување и иновации', 'https://ec.europa.eu/programmes/horizon2020/'),
-- Banking sources
('ProCredit Основна', 'ProCredit Bank основни услуги', 'https://www.procredit-holding.com/home/about-us/procredit-banks/procredit-bank-north-macedonia.html'),
-- Re-adding the specific URLs you mentioned that were missing
('EIT Food Blog', 'Платформа за иновации во храна со повици за финансирање и обуки', 'https://www.eitfood.eu/blog/p2?theme%5B0%5D=224112'),
('Национална Агенција за Erasmus+', 'Официјална агенција за имплементација на Erasmus+ во Северна Македонија', 'https://na.org.mk/'),
-- Additional missing sources from aggregate.js
('Launchub Акцелератор', 'Стартап акцелератор и инвестициски програми', 'https://launchub.bg'),
('CFCD Основна', 'Централен завод за финансирање и договарање', 'https://cfcd.finance.gov.mk'),
('CFCD Finance IPA', 'CFCD портал за IPA програми', 'https://cfcd.finance.gov.mk/?page_id=4750&lang=en');